### ISSUE TITLE
A error when using   null_space = null_space.transpose(0, 1).view(-1, size[1], size[2], size[3])

### ISSUE THREAD

**Issue by wanjundegithub** [siahuat0727/RePr#10]
File "main.py", line 158, in reinitialize
    null_space = null_space.transpose(0, 1).view(-1, size[1], size[2], size[3])
TypeError: view() takes at most 2 arguments (4 given)
how can i fix it?thank you for solving the problem.

**Comment by siahuat0727** [comment]
#8
