### ISSUE TITLE
Bug:  transpose(0, 1) ->  transpose(1, 0)

### ISSUE THREAD

**Issue by zeng-hello-world** [siahuat0727/RePr#3]
[https://github.com/siahuat0727/RePr/blob/master/main.py](https://github.com/siahuat0727/RePr/blob/master/main.py)
# main.py  line 179 : transpose(0, 1) ->  transpose(1, 0)

**Comment by siahuat0727** [comment]
Hi, thank you for checking it for me! 
But these two seem to be equal? [torch.transpose](https://pytorch.org/docs/stable/torch.html#torch.transpose)
By the way, [torch.t](https://pytorch.org/docs/stable/torch.html#torch.t) looks better here since `null_space` is a 2D-tensor.
