### ISSUE TITLE
How does this re-produce code in experiment performance?

### ISSUE THREAD

**Issue by machanic** [siahuat0727/RePr#5]
Does this code fully re-reproduce the experiment result of original author' paper?

**Comment by siahuat0727** [comment]
Sorry for the late reply, I just had time to fix the bug and run it again.
You can see README.md for the result.
Please let me know if you have any further questions or suggestions.

**Comment by machanic** [comment]
@siahuat0727 Do you mean you **have fixed** all the bugs in the code, so it fully reproduce the result of original paper?

**Comment by siahuat0727** [comment]
@sharpstill 
I just fixed bugs that I knew about.
As shown in README.md and my blog, it can't fully reproduce the results.
You may check the [discussion on reddit](https://www.reddit.com/r/MachineLearning/comments/ayh2hf/r_repr_improved_training_of_convolutional_filters/?ref=readnext) for more details.

**Comment by machanic** [comment]
@siahuat0727 Does the original paper's author release any source code?

**Comment by siahuat0727** [comment]
Hi,
please check the discussion link above, thanks!
