### ISSUE TITLE
how to solve "most of the filters pruned is in the earlier convolutional layer"?

### ISSUE THREAD

**Issue by xiezihao123** [siahuat0727/RePr#7]

**Comment by siahuat0727** [comment]
Hi,
I am just a ML beginner trying to re-implement the results of RePr paper :blush: .
If the issue isn't about pointing out my implementation errors or giving some suggestions, please refer to [reddit discussion](https://www.reddit.com/r/MachineLearning/comments/ayh2hf/r_repr_improved_training_of_convolutional_filters/emjl3tl/).
All the best.

**Comment by xiezihao123** [comment]
这个图精度已经80+了，后面的表的精度还都是70+，这是什么原因？




------------------ 原始邮件 ------------------
发件人: "siahuat0727"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午5:39
收件人: "siahuat0727/RePr"<RePr@noreply.github.com>;
抄送: "2216564763"<2216564763@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [siahuat0727/RePr] how to solve "most of the filters pruned is inthe earlier convolutional layer"? (#7)




Hi,
 I am just a ML beginner trying to re-implement the results of RePr paper  .
 If the issue isn't about pointing out my implementation errors or giving some suggestions, please refer to reddit discussion.
 All the best.

**Comment by siahuat0727** [comment]
噢我曾经注意到这件事情但又一直忘记，你是指作者论文 std 和 repr 的图和结果吧？
我觉得这图用了 KD 和 KD+RePr 在比。。。

![image](https://user-images.githubusercontent.com/17688111/57348052-37ab2f00-7187-11e9-84bc-e19241220671.png)

![image](https://user-images.githubusercontent.com/17688111/57347993-00d51900-7187-11e9-8d2a-44248351cfe4.png)

**Comment by xiezihao123** [comment]
嗯嗯，还有一个问题就是，你的代码里用clamp对权值向量里每个元素做了截断，截断之后可能出现的问题是向量不再正交。作者所说的截断会不会是对整个向量的长度做一个截断？




------------------ 原始邮件 ------------------
发件人: "siahuat0727"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 中午11:50
收件人: "siahuat0727/RePr"<RePr@noreply.github.com>;
抄送: "2216564763"<2216564763@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [siahuat0727/RePr] how to solve "most of the filters pruned is inthe earlier convolutional layer"? (#7)




噢我曾经注意到这件事情但又一直忘记，你是指作者论文 std 和 repr 的图和结果吧？
 我觉得这图用了 std 和 KD+RePr 在比。。。

**Comment by siahuat0727** [comment]
作者给我的感觉是，重点不在于如何初始化，而是把相对较差的 filters 给删了再重新初始化。

**Comment by xiezihao123** [comment]
但是其实我改变你的初始化方式，精度就还不如你的精度。不知道作者什么时候开源，就这个标准的72%都没弄出来。


 
---Original---
