### ISSUE TITLE
a error when using "torch.from_numpy(null_space).cuda()"

### ISSUE THREAD

**Issue by xiezihao123** [siahuat0727/RePr#8]
![image](https://user-images.githubusercontent.com/33917659/57266372-365a0380-70ae-11e9-8534-d5583de8e9fe.png)

**Comment by xiezihao123** [comment]
the null_space is [] in the first loop

**Comment by siahuat0727** [comment]
Hi,
I thought this code would handle null_space being empty.
What is your PyTorch version? 
I can run it with PyTorch 1.0.1:
```
>>> x = qr_null(np.random.randn(4, 3))
>>> x
array([], shape=(3, 0), dtype=float64)
>>> x = torch.from_numpy(x).cuda()
>>> x = x.transpose(0,1).view(-1,3)
>>> x
tensor([], device='cuda:0', size=(0, 3), dtype=torch.float64)
```

**Comment by xiezihao123** [comment]
My PyTorch version is 0.4.0。Now，I have another question , how can you make sure  the three-layer vanilla' stride is 1 instead of 2?

**Comment by siahuat0727** [comment]
Hi,
I don't think I can solve the compatibility problem gracefully since I am using PyTorch 1.0.1.
You can use an if-else statement to skip the unnecessary part.

I am not sure that the vanilla model architecture is the same as paper.
But I don't think that's the key point of not getting a good result.
You can explore different model architectures to check the differences.

**Comment by xiezihao123** [comment]
主要是如果步长为2，最后一层全连接层为512x10，如果是1，最后一层为32768x10，显然后面的过拟合会比较严重






------------------ 原始邮件 ------------------
发件人: "siahuat0727"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 中午11:43
收件人: "siahuat0727/RePr"<RePr@noreply.github.com>;
抄送: "2216564763"<2216564763@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [siahuat0727/RePr] a error when using"torch.from_numpy(null_space).cuda()" (#8)




Hi,
 I don't think I can solve the compatibility problem gracefully since I am using PyTorch 1.0.1.
 You can use an if-else statement to skip the unnecessary part.
 
I am not sure that the vanilla model architecture is the same as paper.
 But I don't think that's the key point of not getting a good result.
 You can explore different model architectures to check the differences.

**Comment by wanjundegithub** [comment]
I came across the same problem, Trying to resize storage that is not resizable at /opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/TH/generic/THStorage.c:183,how can I fix it?or just delete the code?does is important to the overall code?

**Comment by wanjundegithub** [comment]
原因找到了，并不是版本的问题，是因为第一层卷积层丢弃的卷积核太多，null_space为空，所以就无法resize,建议按作者要求加一个if elif语句来避免这种情况。

**Comment by siahuat0727** [comment]
@wanjundegithub
Hihi,
感谢回报，对应这篇 Issue 的 commit [88a976f](https://github.com/siahuat0727/RePr/commit/88a976fd240085e86c621c4a39e1ff1487e3306c) 应该已经解决这问题咯，抱歉那时没说清楚。
另外之前会说是版本问题是因为 PyTorch 1.0.1 可以对空值进行 resize 噢。（详细看上面例子）
